Traceback (most recent call last):
  File "/home/pi/weather-station/weather_station_byo.py", line 6, in <module>
    import bme280_sensor
  File "/home/pi/weather-station/bme280_sensor.py", line 9, in <module>
    bme280.load_calibration_params(bus,address)
  File "/usr/local/lib/python3.7/dist-packages/bme280/__init__.py", line 153, in load_calibration_params
    compensation_params.dig_T1 = read.unsigned_short(0x88)
  File "/usr/local/lib/python3.7/dist-packages/bme280/reader.py", line 40, in unsigned_short
    return self._bus.read_word_data(self._address, register) & 0xffff
  File "/usr/local/lib/python3.7/dist-packages/smbus2/smbus2.py", line 474, in read_word_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
/usr/lib/python3/dist-packages/gpiozero/pins/pi.py:156: SPISoftwareFallback: failed to initialize hardware SPI, falling back to software (error was: [Errno 2] No such file or directory)
  'software (error was: %s)' % str(e)))
Traceback (most recent call last):
  File "/home/pi/weather-station/weather_station_byo.py", line 106, in <module>
    store_directions.append(wind_direction_byo.get_value())
  File "/home/pi/weather-station/wind_direction_byo.py", line 61, in get_value
    return get_average(data)
  File "/home/pi/weather-station/wind_direction_byo.py", line 37, in get_average
    s = sin_sum / flen
ZeroDivisionError: float division by zero
/usr/lib/python3/dist-packages/gpiozero/pins/pi.py:156: SPISoftwareFallback: failed to initialize hardware SPI, falling back to software (error was: [Errno 2] No such file or directory)
  'software (error was: %s)' % str(e)))
Traceback (most recent call last):
  File "/home/pi/weather-station/weather_station_byo.py", line 106, in <module>
    store_directions.append(wind_direction_byo.get_value())
  File "/home/pi/weather-station/wind_direction_byo.py", line 61, in get_value
    return get_average(data)
  File "/home/pi/weather-station/wind_direction_byo.py", line 37, in get_average
    s = sin_sum / flen
ZeroDivisionError: float division by zero
/usr/lib/python3/dist-packages/gpiozero/pins/pi.py:156: SPISoftwareFallback: failed to initialize hardware SPI, falling back to software (error was: [Errno 2] No such file or directory)
  'software (error was: %s)' % str(e)))
Traceback (most recent call last):
  File "/home/pi/weather-station/weather_station_byo.py", line 106, in <module>
    store_directions.append(wind_direction_byo.get_value())
  File "/home/pi/weather-station/wind_direction_byo.py", line 61, in get_value
    return get_average(data)
  File "/home/pi/weather-station/wind_direction_byo.py", line 37, in get_average
    s = sin_sum / flen
ZeroDivisionError: float division by zero
/usr/lib/python3/dist-packages/gpiozero/pins/pi.py:156: SPISoftwareFallback: failed to initialize hardware SPI, falling back to software (error was: [Errno 2] No such file or directory)
  'software (error was: %s)' % str(e)))
Traceback (most recent call last):
  File "/home/pi/weather-station/weather_station_byo.py", line 106, in <module>
    store_directions.append(wind_direction_byo.get_value())
  File "/home/pi/weather-station/wind_direction_byo.py", line 61, in get_value
    return get_average(data)       
  File "/home/pi/weather-station/wind_direction_byo.py", line 37, in get_average
    s = sin_sum / flen
ZeroDivisionError: float division by zero
/usr/lib/python3/dist-packages/gpiozero/pins/pi.py:156: SPISoftwareFallback: failed to initialize hardware SPI, falling back to software (error was: [Errno 2] No such file or directory)
  'software (error was: %s)' % str(e)))
Traceback (most recent call last):
  File "/home/pi/weather-station/weather_station_byo.py", line 106, in <module>
    store_directions.append(wind_direction_byo.get_value())
  File "/home/pi/weather-station/wind_direction_byo.py", line 61, in get_value
    return get_average(data)       
  File "/home/pi/weather-station/wind_direction_byo.py", line 37, in get_average
    s = sin_sum / flen
ZeroDivisionError: float division by zero
